name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install --yes gdc

      - name: Build and test
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
