name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and test
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
