name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Gaya
        run: |
          apt-get install gdc
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Test examples
        run: ./scripts/test.sh
