name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install gdc ruby

      - name: Build Gaya
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Test examples
        run: ruby ./scripts/test.rb
